import 'package:get/get.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FriendsModelData {
/*
{
  "user_id": "4",
  "firstname": "Souvik",
  "lastname": "Nath",
  "img": "1563466460.jpeg"
}
*/

  String? userId;
  String? firstname;
  String? lastname;
  String? img;
  RxBool isSelected = false.obs;

  FriendsModelData({
    this.userId,
    this.firstname,
    this.lastname,
    this.img,
  });
  FriendsModelData.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    img = json['img']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['img'] = img;
    return data;
  }
}

class FriendsModel {
/*
{
  "data": [
    {
      "user_id": "4",
      "firstname": "Souvik",
      "lastname": "Nath",
      "img": "1563466460.jpeg"
    }
  ]
}
*/

  List<FriendsModelData?>? data;

  FriendsModel({
    this.data,
  });
  FriendsModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <FriendsModelData>[];
      v.forEach((v) {
        arr0.add(FriendsModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
