///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GroupModelData {
/*
{
  "group_id": "59",
  "group_title": "Test Group",
  "created_by": "3272"
}
*/

  String? groupId;
  String? groupTitle;
  String? createdBy;

  GroupModelData({
    this.groupId,
    this.groupTitle,
    this.createdBy,
  });

  GroupModelData.fromJson(Map<String, dynamic> json) {
    groupId = json['group_id']?.toString();
    groupTitle = json['group_title']?.toString();
    createdBy = json['created_by']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['group_id'] = groupId;
    data['group_title'] = groupTitle;
    data['created_by'] = createdBy;
    return data;
  }
}

class GroupModel {
/*
{
  "type": "success",
  "data": [
    {
      "group_id": "59",
      "group_title": "Test Group",
      "created_by": "3272"
    }
  ]
}
*/

  String? type;
  List<GroupModelData?>? data;

  GroupModel({
    this.type,
    this.data,
  });

  GroupModel.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GroupModelData>[];
      v.forEach((v) {
        arr0.add(GroupModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
