///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CommentModelCommentList {
/*
{
  "comment": "Testing ",
  "date": "2022-09-27 03:59:00",
  "comment_id": "1877",
  "user_id": "5",
  "firstname": "LENNOX",
  "img": "1620924962.jpg",
  "lastname": "DAVIDSON"
}
*/

  String? comment;
  String? date;
  String? commentId;
  String? userId;
  String? firstname;
  String? img;
  String? lastname;

  CommentModelCommentList({
    this.comment,
    this.date,
    this.commentId,
    this.userId,
    this.firstname,
    this.img,
    this.lastname,
  });
  CommentModelCommentList.fromJson(Map<String, dynamic> json) {
    comment = json['comment']?.toString();
    date = json['date']?.toString();
    commentId = json['comment_id']?.toString();
    userId = json['user_id']?.toString();
    firstname = json['firstname']?.toString();
    img = json['img']?.toString();
    lastname = json['lastname']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['comment'] = comment;
    data['date'] = date;
    data['comment_id'] = commentId;
    data['user_id'] = userId;
    data['firstname'] = firstname;
    data['img'] = img;
    data['lastname'] = lastname;
    return data;
  }
}

class CommentModel {
/*
{
  "type": "success",
  "comment_list": [
    {
      "comment": "Testing ",
      "date": "2022-09-27 03:59:00",
      "comment_id": "1877",
      "user_id": "5",
      "firstname": "LENNOX",
      "img": "1620924962.jpg",
      "lastname": "DAVIDSON"
    }
  ],
  "next_start": 20
}
*/

  String? type;
  List<CommentModelCommentList?>? commentList;
  int? nextStart;

  CommentModel({
    this.type,
    this.commentList,
    this.nextStart,
  });
  CommentModel.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['comment_list'] != null) {
      final v = json['comment_list'];
      final arr0 = <CommentModelCommentList>[];
      v.forEach((v) {
        arr0.add(CommentModelCommentList.fromJson(v));
      });
      commentList = arr0;
    }
    nextStart = json['next_start']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (commentList != null) {
      final v = commentList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['comment_list'] = arr0;
    }
    data['next_start'] = nextStart;
    return data;
  }
}
