import 'package:flutter/cupertino.dart';
import 'package:wghdfm_java/model/to_user_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostModelFeedPromoteGroupDetails {
/*
{
  "group_id": "102",
  "group_title": "Cyclone Alert Group Private",
  "cover_pic": "1483377260.JPG",
  "created_by": "3338",
  "created_on": "2023-06-16",
  "is_active": "Y",
  "type": "P",
  "user_id": "3338",
  "firstname": "darshil",
  "lastname": "rabadiya "
}
*/

  String? groupId;
  String? groupTitle;
  String? groupDescription;
  String? coverPic;
  String? createdBy;
  String? createdOn;
  String? isActive;
  String? type;
  String? userId;
  String? firstname;
  String? lastname;

  PostModelFeedPromoteGroupDetails({
    this.groupId,
    this.groupTitle,
    this.groupDescription,
    this.coverPic,
    this.createdBy,
    this.createdOn,
    this.isActive,
    this.type,
    this.userId,
    this.firstname,
    this.lastname,
  });

  PostModelFeedPromoteGroupDetails.fromJson(Map<String, dynamic> json) {
    groupId = json['group_id']?.toString();
    groupTitle = json['group_title']?.toString();
    groupDescription = json['group_description']?.toString();
    coverPic = json['cover_pic']?.toString();
    createdBy = json['created_by']?.toString();
    createdOn = json['created_on']?.toString();
    isActive = json['is_active']?.toString();
    type = json['type']?.toString();
    userId = json['user_id']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['group_id'] = groupId;
    data['group_title'] = groupTitle;
    data['group_description'] = groupDescription;
    data['cover_pic'] = coverPic;
    data['created_by'] = createdBy;
    data['created_on'] = createdOn;
    data['is_active'] = isActive;
    data['type'] = type;
    data['user_id'] = userId;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    return data;
  }
}

class PostModelFeedLatestComments {
/*
{
  "comment": "testing ",
  "date": "2022-12-27 23:41:38",
  "comment_id": "1983",
  "user_id": "4",
  "firstname": "Souvik",
  "img": "1563466460.jpeg",
  "lastname": "Nath"
}
*/

  String? comment;
  String? date;
  String? commentId;
  String? userId;
  String? firstname;
  String? img;
  String? lastname;

  PostModelFeedLatestComments({
    this.comment,
    this.date,
    this.commentId,
    this.userId,
    this.firstname,
    this.img,
    this.lastname,
  });

  PostModelFeedLatestComments.fromJson(Map<String, dynamic> json) {
    comment = json['comment']?.toString();
    date = json['date']?.toString();
    commentId = json['comment_id']?.toString();
    userId = json['user_id']?.toString();
    firstname = json['firstname']?.toString();
    img = json['img']?.toString();
    lastname = json['lastname']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['comment'] = comment;
    data['date'] = date;
    data['comment_id'] = commentId;
    data['user_id'] = userId;
    data['firstname'] = firstname;
    data['img'] = img;
    data['lastname'] = lastname;
    return data;
  }
}

class TaggedUsers {
/*
{
  "comment": "testing ",
  "date": "2022-12-27 23:41:38",
  "comment_id": "1983",
  "user_id": "4",
  "firstname": "Souvik",
  "img": "1563466460.jpeg",
  "lastname": "Nath"
}
*/

  String? profileId;
  String? profileImg;
  String? profileName;

  TaggedUsers({
    this.profileImg,
    this.profileId,
    this.profileName,
  });

  TaggedUsers.fromJson(Map<String, dynamic> json) {
    profileName = json['profile_name']?.toString();
    profileId = json['profile_id']?.toString();
    profileImg = json['profile_img']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['profile_name'] = profileName;
    data['profile_id'] = profileId;
    data['profile_img'] = profileImg;
    return data;
  }
}

class PostModelFeed {
/*
{
  "id": "9211",
  "name": "Romil Mavani",
  "image": null,
  "owner_id": "3308",
  "all_tag_user_list": [
    null
  ],
  "status": "",
  "profilePic": "https://wghdfm.s3.amazonaws.com/thumb/1671061316.jpg",
  "timeStamp": "June 16, 2023, 3:18 pm",
  "url": "",
  "vimg": "",
  "is_fav": 0,
  "is_like": 0,
  "count_like": "0",
  "count_comment": 0,
  "latest_comments": [
    {
      "comment": "testing ",
      "date": "2022-12-27 23:41:38",
      "comment_id": "1983",
      "user_id": "4",
      "firstname": "Souvik",
      "img": "1563466460.jpeg",
      "lastname": "Nath"
    }
  ],
  "youtube_id": "",
  "video": "",
  "video_thumb": "",
  "shared_post_user_id": "",
  "shared_post_user": "",
  "media": "",
  "promote_group_details": {
    "group_id": "102",
    "group_title": "Cyclone Alert Group Private",
    "cover_pic": "1483377260.JPG",
    "created_by": "3338",
    "created_on": "2023-06-16",
    "is_active": "Y",
    "type": "P",
    "user_id": "3338",
    "firstname": "darshil",
    "lastname": "rabadiya "
  }
}
*/

  String? id;
  String? name;
  String? image;
  String? ownerId;
  List<TaggedUsers>? allTagUserList;
  String? status;
  String? profilePic;
  String? timeStamp;
  String? url;
  String? vimg;
  int? isFav;
  int? isLike;
  String? countLike;
  int? countComment;
  ToUserId? toUserIdDetails;
  List<PostModelFeedLatestComments?>? latestComments;
  String? youtubeId;
  String? video;
  String? videoThumb;
  String? sharedPostUserId;
  String? sharedPostUser;
  String? media;
  PostModelFeedPromoteGroupDetails? promoteGroupDetails;
  TextEditingController commentTextController = TextEditingController();

  PostModelFeed({
    this.id,
    this.name,
    this.image,
    this.ownerId,
    this.allTagUserList,
    this.status,
    this.profilePic,
    this.timeStamp,
    this.url,
    this.vimg,
    this.isFav,
    this.isLike,
    this.countLike,
    this.countComment,
    this.toUserIdDetails,
    this.latestComments,
    this.youtubeId,
    this.video,
    this.videoThumb,
    this.sharedPostUserId,
    this.sharedPostUser,
    this.media,
    this.promoteGroupDetails,
  });

  PostModelFeed.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    ownerId = json['owner_id']?.toString();
    if (json['all_tag_user_list'] != null) {
      final v = json['all_tag_user_list'];
      final arr0 = <TaggedUsers>[];
      v.forEach((v) {
        arr0.add(TaggedUsers.fromJson(v));
      });
      allTagUserList = arr0;
    }
    status = json['status']?.toString();
    profilePic = json['profilePic']?.toString();
    timeStamp = json['timeStamp']?.toString();
    url = json['url']?.toString();
    vimg = json['vimg']?.toString();
    isFav = json['is_fav']?.toInt();
    isLike = json['is_like']?.toInt();
    countLike = json['count_like']?.toString();
    countComment = json['count_comment']?.toInt();
    if (json['latest_comments'] != null) {
      final v = json['latest_comments'];
      final arr0 = <PostModelFeedLatestComments>[];
      v.forEach((v) {
        arr0.add(PostModelFeedLatestComments.fromJson(v));
      });
      latestComments = arr0;
    }
    youtubeId = json['youtube_id']?.toString();
    video = json['video']?.toString();
    videoThumb = json['video_thumb']?.toString();
    sharedPostUserId = json['shared_post_user_id']?.toString();
    sharedPostUser = json['shared_post_user']?.toString();
    media = json['media']?.toString();
    promoteGroupDetails = (json['promote_group_details'] != null) ? PostModelFeedPromoteGroupDetails.fromJson(json['promote_group_details']) : null;
    toUserIdDetails = (json['to_user_details'] != null) ? ToUserId.fromJson(json['to_user_details']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['owner_id'] = ownerId;
    data['status'] = status;
    data['profilePic'] = profilePic;
    data['timeStamp'] = timeStamp;
    data['url'] = url;
    data['vimg'] = vimg;
    data['is_fav'] = isFav;
    data['is_like'] = isLike;
    data['count_like'] = countLike;
    data['count_comment'] = countComment;
    if (latestComments != null) {
      final v = latestComments;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['latest_comments'] = arr0;
    }
    data['youtube_id'] = youtubeId;
    data['video'] = video;
    data['video_thumb'] = videoThumb;
    data['shared_post_user_id'] = sharedPostUserId;
    data['shared_post_user'] = sharedPostUser;
    data['media'] = media;
    if (promoteGroupDetails != null) {
      data['promote_group_details'] = promoteGroupDetails!.toJson();
    }
    return data;
  }
}

class PostModel {
/*
{
  "feed": [
    {
      "id": "9211",
      "name": "Romil Mavani",
      "image": null,
      "owner_id": "3308",
      "all_tag_user_list": [
        null
      ],
      "status": "",
      "profilePic": "https://wghdfm.s3.amazonaws.com/thumb/1671061316.jpg",
      "timeStamp": "June 16, 2023, 3:18 pm",
      "url": "",
      "vimg": "",
      "is_fav": 0,
      "is_like": 0,
      "count_like": "0",
      "count_comment": 0,
      "latest_comments": [
        {
          "comment": "testing ",
          "date": "2022-12-27 23:41:38",
          "comment_id": "1983",
          "user_id": "4",
          "firstname": "Souvik",
          "img": "1563466460.jpeg",
          "lastname": "Nath"
        }
      ],
      "youtube_id": "",
      "video": "",
      "video_thumb": "",
      "shared_post_user_id": "",
      "shared_post_user": "",
      "media": "",
      "promote_group_details": {
        "group_id": "102",
        "group_title": "Cyclone Alert Group Private",
        "cover_pic": "1483377260.JPG",
        "created_by": "3338",
        "created_on": "2023-06-16",
        "is_active": "Y",
        "type": "P",
        "user_id": "3338",
        "firstname": "darshil",
        "lastname": "rabadiya "
      }
    }
  ]
}
*/

  List<PostModelFeed?>? feed;

  PostModel({
    this.feed,
  });

  PostModel.fromJson(Map<String, dynamic> json) {
    if (json['feed'] != null) {
      final v = json['feed'];
      final arr0 = <PostModelFeed>[];
      v.forEach((v) {
        arr0.add(PostModelFeed.fromJson(v));
      });
      feed = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (feed != null) {
      final v = feed;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['feed'] = arr0;
    }
    return data;
  }
}
