/*
// To parse this JSON data, do
//
//     final groups = groupsFromJson(jsonString);

import 'dart:convert';

class Groups {
  Groups({
    this.groups,
  });

  List<Group>? groups;

  Groups copyWith({
    List<Group>? groups,
  }) =>
      Groups(
        groups: groups ?? this.groups,
      );

  factory Groups.fromRawJson(String str) => Groups.fromJson(json.decode(str));

  String toRawJson() => json.encode(toJson());

  factory Groups.fromJson(Map<String, dynamic> json) => Groups(
        groups: json["feed"] == null
            ? null
            : List<Group>.from(json["feed"].map((x) => Group.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        "feed": groups == null
            ? null
            : List<dynamic>.from(groups!.map((x) => x.toJson())),
      };
}

class Group {
  Group({
    this.name,
    this.groupId,
    this.ownerId,
    this.profilePic,
    this.createdOn,
    this.type,
    this.sendReqButton,
    this.isAdmin,
    this.postAbility,
  });

  String? name;
  String? groupId;
  String? ownerId;
  String? profilePic;
  String? createdOn;
  String? type;
  String? sendReqButton;
  String? isAdmin;
  String? postAbility;

  Group copyWith({
    String? name,
    String? groupId,
    String? ownerId,
    String? profilePic,
    String? createdOn,
    String? type,
    String? sendReqButton,
    String? isAdmin,
    String? postAbility,
  }) =>
      Group(
        name: name ?? this.name,
        groupId: groupId ?? this.groupId,
        ownerId: ownerId ?? this.ownerId,
        profilePic: profilePic ?? this.profilePic,
        createdOn: createdOn ?? this.createdOn,
        type: type ?? this.type,
        sendReqButton: sendReqButton ?? this.sendReqButton,
        isAdmin: isAdmin ?? this.isAdmin,
        postAbility: postAbility ?? this.postAbility,
      );

  factory Group.fromRawJson(String str) => Group.fromJson(json.decode(str));

  String toRawJson() => json.encode(toJson());

  factory Group.fromJson(Map<String, dynamic> json) => Group(
        name: json["name"] == null ? null : json["name"],
        groupId: json["group_id"] == null ? null : json["group_id"],
        ownerId: json["owner_id"] == null ? null : json["owner_id"],
        profilePic: json["profilePic"] == null ? null : json["profilePic"],
        createdOn: json["created_on"] == null ? null : json["created_on"],
        type: json["type"] == null ? null : json["type"],
        sendReqButton:
            json["send_req_button"] == null ? null : json["send_req_button"],
        isAdmin: json["is_admin"] == null ? null : json["is_admin"],
        postAbility: json["post_ability"] == null ? null : json["post_ability"],
      );

  Map<String, dynamic> toJson() => {
        "name": name == null ? null : name,
        "group_id": groupId == null ? null : groupId,
        "owner_id": ownerId == null ? null : ownerId,
        "profilePic": profilePic == null ? null : profilePic,
        "created_on": createdOn == null ? null : createdOn,
        "type": type == null ? null : type,
        "send_req_button": sendReqButton == null ? null : sendReqButton,
        "is_admin": isAdmin == null ? null : isAdmin,
        "post_ability": postAbility == null ? null : postAbility,
      };
}
*/

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Group {
/*
{
  "name": "test group created from api 1",
  "group_id": "68",
  "owner_id": "3272",
  "profilePic": "https://wghdfm.s3.amazonaws.com/thumb/1674711952.jpeg",
  "created_on": "28 February 2023",
  "type": "O",
  "send_req_button": "N",
  "is_admin": "Y",
  "post_ability": "Y"
}
*/

  String? name;
  String? groupId;
  String? ownerId;
  String? profilePic;
  String? createdOn;
  String? type;
  String? sendReqButton;
  String? isAdmin;
  String? postAbility;

  Group({
    this.name,
    this.groupId,
    this.ownerId,
    this.profilePic,
    this.createdOn,
    this.type,
    this.sendReqButton,
    this.isAdmin,
    this.postAbility,
  });
  Group.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    groupId = json['group_id']?.toString();
    ownerId = json['owner_id']?.toString();
    profilePic = json['profilePic']?.toString();
    createdOn = json['created_on']?.toString();
    type = json['type']?.toString();
    sendReqButton = json['send_req_button']?.toString();
    isAdmin = json['is_admin']?.toString();
    postAbility = json['post_ability']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['group_id'] = groupId;
    data['owner_id'] = ownerId;
    data['profilePic'] = profilePic;
    data['created_on'] = createdOn;
    data['type'] = type;
    data['send_req_button'] = sendReqButton;
    data['is_admin'] = isAdmin;
    data['post_ability'] = postAbility;
    return data;
  }
}

class Groups {
/*
{
  "type": "success",
  "data": [
    {
      "name": "test group created from api 1",
      "group_id": "68",
      "owner_id": "3272",
      "profilePic": "https://wghdfm.s3.amazonaws.com/thumb/1674711952.jpeg",
      "created_on": "28 February 2023",
      "type": "O",
      "send_req_button": "N",
      "is_admin": "Y",
      "post_ability": "Y"
    }
  ]
}
*/

  String? type;
  List<Group?>? data;

  Groups({
    this.type,
    this.data,
  });
  Groups.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <Group>[];
      v.forEach((v) {
        arr0.add(Group.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
