///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GroupMemberModelData {
/*
{
  "firstname": "Mofijul",
  "lastname": "Hasan",
  "img": "1674711952.jpeg",
  "status": "o",
  "address": "",
  "birthday": null,
  "user_type": "Y",
  "church": "",
  "user_id": "3272",
  "gender": "M",
  "is_active": "Y",
  "group_members_id": "114",
  "is_admin": "U"
}
*/

  String? firstname;
  String? lastname;
  String? img;
  String? status;
  String? address;
  String? birthday;
  String? userType;
  String? church;
  String? userId;
  String? gender;
  String? isActive;
  String? groupMembersId;
  String? isAdmin;

  GroupMemberModelData({
    this.firstname,
    this.lastname,
    this.img,
    this.status,
    this.address,
    this.birthday,
    this.userType,
    this.church,
    this.userId,
    this.gender,
    this.isActive,
    this.groupMembersId,
    this.isAdmin,
  });
  GroupMemberModelData.fromJson(Map<String, dynamic> json) {
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    img = json['img']?.toString();
    status = json['status']?.toString();
    address = json['address']?.toString();
    birthday = json['birthday']?.toString();
    userType = json['user_type']?.toString();
    church = json['church']?.toString();
    userId = json['user_id']?.toString();
    gender = json['gender']?.toString();
    isActive = json['is_active']?.toString();
    groupMembersId = json['group_members_id']?.toString();
    isAdmin = json['is_admin']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['img'] = img;
    data['status'] = status;
    data['address'] = address;
    data['birthday'] = birthday;
    data['user_type'] = userType;
    data['church'] = church;
    data['user_id'] = userId;
    data['gender'] = gender;
    data['is_active'] = isActive;
    data['group_members_id'] = groupMembersId;
    data['is_admin'] = isAdmin;
    return data;
  }
}

class GroupMemberModel {
/*
{
  "type": "success",
  "data": [
    {
      "firstname": "Mofijul",
      "lastname": "Hasan",
      "img": "1674711952.jpeg",
      "status": "o",
      "address": "",
      "birthday": null,
      "user_type": "Y",
      "church": "",
      "user_id": "3272",
      "gender": "M",
      "is_active": "Y",
      "group_members_id": "114",
      "is_admin": "U"
    }
  ]
}
*/

  String? type;
  List<GroupMemberModelData?>? data;

  GroupMemberModel({
    this.type,
    this.data,
  });
  GroupMemberModel.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GroupMemberModelData>[];
      v.forEach((v) {
        arr0.add(GroupMemberModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
