///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class ToUserId {
/*
{
  "firstname": "darshil",
  "lastname": "rabadiya ",
  "user_id": "3338",
  "img": "1671083924.jpg"
} 
*/

  String? firstname;
  String? lastname;
  String? userId;
  String? img;

  ToUserId({
    this.firstname,
    this.lastname,
    this.userId,
    this.img,
  });
  ToUserId.fromJson(Map<String, dynamic> json) {
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    userId = json['user_id']?.toString();
    img = json['img']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['user_id'] = userId;
    data['img'] = img;
    return data;
  }
}
