///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AllMessagesModelMessagesData {
/*
{
  "id": "1872",
  "sub_id": "1872",
  "sender": "3272",
  "receipt": "3308",
  "message": "hello tttt",
  "notify": "N",
  "date": "2023-05-10 16:50:20",
  "user_id": "3272",
  "firstname": "Mofijul",
  "user_type": "Y",
  "church": "",
  "lastname": "Hasan",
  "img": "1674711952.jpeg"
}
*/

  String? id;
  String? subId;
  String? sender;
  String? receipt;
  String? message;
  String? notify;
  String? date;
  String? userId;
  String? firstname;
  String? userType;
  String? church;
  String? lastname;
  String? img;

  AllMessagesModelMessagesData({
    this.id,
    this.subId,
    this.sender,
    this.receipt,
    this.message,
    this.notify,
    this.date,
    this.userId,
    this.firstname,
    this.userType,
    this.church,
    this.lastname,
    this.img,
  });
  AllMessagesModelMessagesData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    subId = json['sub_id']?.toString();
    sender = json['sender']?.toString();
    receipt = json['receipt']?.toString();
    message = json['message']?.toString();
    notify = json['notify']?.toString();
    date = json['date']?.toString();
    userId = json['user_id']?.toString();
    firstname = json['firstname']?.toString();
    userType = json['user_type']?.toString();
    church = json['church']?.toString();
    lastname = json['lastname']?.toString();
    img = json['img']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['sub_id'] = subId;
    data['sender'] = sender;
    data['receipt'] = receipt;
    data['message'] = message;
    data['notify'] = notify;
    data['date'] = date;
    data['user_id'] = userId;
    data['firstname'] = firstname;
    data['user_type'] = userType;
    data['church'] = church;
    data['lastname'] = lastname;
    data['img'] = img;
    return data;
  }
}

class AllMessagesModel {
/*
{
  "type": "success",
  "messages_data": [
    {
      "id": "1872",
      "sub_id": "1872",
      "sender": "3272",
      "receipt": "3308",
      "message": "hello tttt",
      "notify": "N",
      "date": "2023-05-10 16:50:20",
      "user_id": "3272",
      "firstname": "Mofijul",
      "user_type": "Y",
      "church": "",
      "lastname": "Hasan",
      "img": "1674711952.jpeg"
    }
  ]
}
*/

  String? type;
  List<AllMessagesModelMessagesData?>? messagesData;

  AllMessagesModel({
    this.type,
    this.messagesData,
  });
  AllMessagesModel.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['messages_data'] != null) {
      final v = json['messages_data'];
      final arr0 = <AllMessagesModelMessagesData>[];
      v.forEach((v) {
        arr0.add(AllMessagesModelMessagesData.fromJson(v));
      });
      messagesData = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (messagesData != null) {
      final v = messagesData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['messages_data'] = arr0;
    }
    return data;
  }
}
