import 'package:wghdfm_java/model/feed_res_obj.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationPostModelFeed {
/*
{
  "id": "8695",
  "name": "Mofijul Hasan",
  "image": null,
  "owner_id": "3272",
  "status": "hello!?",
  "profilePic": "https://wghdfm.s3.amazonaws.com/thumb/1674711952.jpeg",
  "timeStamp": "April 2, 2023, 3:08 pm",
  "url": "",
  "vimg": "",
  "is_fav": 0,
  "is_like": 0,
  "count_like": "0",
  "count_comment": 0,
  "latest_comments": null,
  "youtube_id": "",
  "video": "",
  "video_thumb": "",
  "shared_post_user_id": "",
  "shared_post_user": "",
  "media": "https://wghdfm.s3.amazonaws.com/wires/1680428318_1.jpg_|_https://wghdfm.s3.amazonaws.com/wires/1680428319_2.jpeg"
}
*/

  String? id;
  String? name;
  String? image;
  String? ownerId;
  String? status;
  String? profilePic;
  String? timeStamp;
  String? url;
  String? vimg;
  int? isFav;
  int? isLike;
  String? countLike;
  int? countComment;
  String? latestComments;
  String? youtubeId;
  String? video;
  String? videoThumb;
  String? sharedPostUserId;
  String? sharedPostUser;
  String? media;

  NotificationPostModelFeed({
    this.id,
    this.name,
    this.image,
    this.ownerId,
    this.status,
    this.profilePic,
    this.timeStamp,
    this.url,
    this.vimg,
    this.isFav,
    this.isLike,
    this.countLike,
    this.countComment,
    this.latestComments,
    this.youtubeId,
    this.video,
    this.videoThumb,
    this.sharedPostUserId,
    this.sharedPostUser,
    this.media,
  });

  NotificationPostModelFeed.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    ownerId = json['owner_id']?.toString();
    status = json['status']?.toString();
    profilePic = json['profilePic']?.toString();
    timeStamp = json['timeStamp']?.toString();
    url = json['url']?.toString();
    vimg = json['vimg']?.toString();
    isFav = json['is_fav']?.toInt();
    isLike = json['is_like']?.toInt();
    countLike = json['count_like']?.toString();
    countComment = json['count_comment']?.toInt();
    latestComments = json['latest_comments']?.toString();
    youtubeId = json['youtube_id']?.toString();
    video = json['video']?.toString();
    videoThumb = json['video_thumb']?.toString();
    sharedPostUserId = json['shared_post_user_id']?.toString();
    sharedPostUser = json['shared_post_user']?.toString();
    media = json['media']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['owner_id'] = ownerId;
    data['status'] = status;
    data['profilePic'] = profilePic;
    data['timeStamp'] = timeStamp;
    data['url'] = url;
    data['vimg'] = vimg;
    data['is_fav'] = isFav;
    data['is_like'] = isLike;
    data['count_like'] = countLike;
    data['count_comment'] = countComment;
    data['latest_comments'] = latestComments;
    data['youtube_id'] = youtubeId;
    data['video'] = video;
    data['video_thumb'] = videoThumb;
    data['shared_post_user_id'] = sharedPostUserId;
    data['shared_post_user'] = sharedPostUser;
    data['media'] = media;
    return data;
  }
}

class NotificationPostModel {
/*
{
  "feed": [
    {
      "id": "8695",
      "name": "Mofijul Hasan",
      "image": null,
      "owner_id": "3272",
      "status": "hello!?",
      "profilePic": "https://wghdfm.s3.amazonaws.com/thumb/1674711952.jpeg",
      "timeStamp": "April 2, 2023, 3:08 pm",
      "url": "",
      "vimg": "",
      "is_fav": 0,
      "is_like": 0,
      "count_like": "0",
      "count_comment": 0,
      "latest_comments": null,
      "youtube_id": "",
      "video": "",
      "video_thumb": "",
      "shared_post_user_id": "",
      "shared_post_user": "",
      "media": "https://wghdfm.s3.amazonaws.com/wires/1680428318_1.jpg_|_https://wghdfm.s3.amazonaws.com/wires/1680428319_2.jpeg"
    }
  ]
}
*/

  List<PostModelFeed?>? feed;

  NotificationPostModel({
    this.feed,
  });

  NotificationPostModel.fromJson(Map<String, dynamic> json) {
    if (json['feed'] != null) {
      final v = json['feed'];
      final arr0 = <PostModelFeed>[];
      v.forEach((v) {
        arr0.add(PostModelFeed.fromJson(v));
      });
      feed = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (feed != null) {
      final v = feed;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['feed'] = arr0;
    }
    return data;
  }
}
